# The following lines are required because standard make does not
# recognize the Objective-C .m suffix.

.SUFFIXES: .o .cpp
.cpp.o:
	$(CC) -c $(DFLAGS) $(CFLAGS) $(INCLUDE) $<


# Macros

BINDIR = ../bin
CC = g++ 
CFLAGS = -O3 -g -Wall -static
INCLUDE = -I. -Isamtools
DFLAGS =  
HEAD = core.h gzstream.h
OBJ = core.o gzstream.o
LIBDIR = samtools
LIB = -L$(LIBDIR) -lbam -lm -lz -lgslcblas -lgsl 


# Explicit rules

all: hic-matrix gtools-hic gtools-overlaps gtools-regions gtools-scans gtools-threaded tools-cols tools-key-expand tools-mergeuniq tools-matrix tools-matrix2 tools-rows tools-table tools-vectors

lbam:
	cd samtools; make libbam.a; cd ..

gtools-threaded: gtools-threaded.cpp gtools-intervals.o $(OBJ) lbam
	$(CC) $(DFLAGS) $(CFLAGS) $(INCLUDE) -std=c++0x -lpthread gtools-intervals.o $(OBJ) -o $(BINDIR)/$@ $< $(LIB)

gtools-%: gtools-%.cpp gtools-intervals.o $(OBJ) lbam
	$(CC) $(DFLAGS) $(CFLAGS) $(INCLUDE) $(OBJ) gtools-intervals.o -o $(BINDIR)/$@ $< $(LIB)

tools-%: tools-%.cpp $(OBJ)
	$(CC) $(DFLAGS) $(CFLAGS) $(INCLUDE) $(OBJ) -o $(BINDIR)/$@ $< $(LIB)

hic-matrix: hic-matrix.cpp
	R CMD SHLIB hic-matrix.cpp
	
clean:
	rm -f samtools/libbam.a *.o *.so $(BINDIR)/*tools-*



