#!/bin/tcsh
#$ -S /bin/tcsh

##
## USAGE: run
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

# shell settings
source ./code/code.main/custom-tcshrc

scripts-send2err "PIPELINE STARTING: `date`"
foreach d (__*)
  ( cd $d; ./run )
end
scripts-send2err "PIPELINE COMPLETED: `date`"

scripts-send2err ""
scripts-send2err "Errors below, if any: "
./code/code.main/pipeline-errors
scripts-send2err ""
scripts-send2err "Done."

