#!/bin/sh

find . -name 'job.*err' -print0 | xargs -0 grep -iE 'error|segmentation|not found|join.*sort|no such file|syntax' 1>&2

find . -name 'job.*out' -print0 | xargs -0 grep -iE 'error|segmentation|not found|join.*sort|no such file|syntax' 1>&2






