#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: smartcat FILES
##

if ($#argv == 0) then
  grep '^##' $0
  exit
endif

set F = ($*)

if (`echo $F[1] | grep -c '\.gz$'` == 0) then
  cat $F
else
  cat $F | gunzip
endif


