#!/bin/tcsh
source ./code/code.main/custom-tcshrc      # customize shell environment

##
## USAGE: scripts-wait-qsub JOB-IDS [SECONDS=5]
##

set job_ids = ($1)
if ($#job_ids == 0) exit

set sec = $2
if ($sec == '') set sec = 5 

set flag = `scripts-create-temp`
echo "touch $flag.done" >> $flag
chmod +x $flag
(qsub -hold_jid `echo $job_ids | tr ' ' ','` -cwd ./$flag) >& /dev/null
while (1)
  sleep $sec
#  ls *.done
  if (-e $flag.done) break
end
rm -f ${flag}*

