#!/bin/tcsh
#$ -S /bin/tcsh
source ./code/code.main/custom-tcshrc    # customize shell environment

##
## USAGE: scripts-qsub-run JOB-PREFIX N-THREADS MEMORY-GB SCRIPT-PATH ARGS ...
##

if ($#argv < 4) then
  grep '^##' $0
  exit
endif

set jpref = $1
set nthreads = $2
set mem = $3
set prog = $4
shift
shift
shift
shift

if (-e $jpref.sh) then
  scripts-send2err "Error: [scripts-qsubmem-run] $jpref.sh already exists, cannot overwrite."
  exit 1
endif
 
scripts-print-cmdline $prog $argv:q >! $jpref.sh
qsub -cwd -l mem_free=${mem}G -l h_vmem=${mem}G -l mem_token=${mem}G -o :$jpref.out -e :$jpref.err -pe threaded $nthreads $jpref.sh >! $jpref.jid
cat $jpref.jid | cut -d' ' -f3





