#!/bin/tcsh

##
## USAGE: pipeline-new-analysis PIPELINE-NAME NEW-PROJECT-DIR
##

if ($#argv != 2) then
  grep '^##' $0
  exit
endif

set pipeline_name = $1
set project_dir = $2

set pipeline_dir = `readlink -f $0 | sed 's/\/[^/]\+$//'`/../pipelines/$pipeline_name
set pipeline_dir = `echo $pipeline_dir | sed 's/[/]\+$//'`    # remove trailing '/'

echo "Copying pipeline structure and code into $project_dir..."
rsync -auv --exclude=results $pipeline_dir/ $project_dir

# TODO: need to create a symbolic link to the code




