#!/bin/tcsh

##
## USAGE: pipeline-checkout PIPELINE-DIR NEW-PROJECT-DIR
##

if ($#argv != 2) then
  grep '^##' $0
  exit
endif

set pipeline_dir = `echo $1 | sed 's/[/]\+$//'`    # remove trailing '/'
set project_dir = $2

echo "Copying general code into $project_dir/code..."
rsync -auv --exclude=results $pipeline_dir/../code $project_dir

echo "Copying pipeline structure and code into $project_dir..."
rsync -auv --exclude=results $pipeline_dir $project_dir




