#!/bin/tcsh
#$ -S /bin/tcsh

##
## USAGE: scripts-qsub-run JOB-PREFIX N-THREADS SCRIPT-PATH ARGS ...
##

if ($#argv < 3) then
  grep '^##' $0
  exit
endif

set jpref = $1
set nthreads = $2
set prog = `which $3`
shift
shift
shift

set script = `mktemp $jpref.XXXXXXXX`
scripts-print-cmdline $prog $argv:q >> $script
qsub -cwd -o $script.out -e $script.err -pe threaded $nthreads ./$script >! $script.jid
cat $script.jid | cut -d' ' -f3

#qsub -cwd -pe threaded $nthreads -o $log.out -e $log.err $prog $argv:q | cut -d' ' -f3




