#!/bin/tcsh
#$ -S /bin/tcsh

##
## USAGE: run
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

echo '----------------------------------------------------------------'
echo '   ARE YOU SURE YOU WANT TO DELETE ALL RESULTS????'
echo '----------------------------------------------------------------'
echo
echo -n 'Type YES to continue, CONTROL-C TO ABORT...'
set y = $<
if ($y != "YES") exit

foreach d (__*)
  ( cd $d; ./clean.tcsh )
end

