#!/bin/tcsh

##
## USAGE: chipseq-stats OUTPUT-FILE PARAMETER-SCRIPT BAM-FILE
##

if ($#argv != 3) then
  grep '^##' $0
  exit
endif

set out = $1
set params = $2
set aln = $3

# set parameters
source $params
if (! $?NSLOTS) then
  set threads = 1
else
  set threads = $NSLOTS
endif

samtools flagstat $bam >! $out



