#!/bin/tcsh
#$ -S /bin/tcsh

##
## USAGE: run
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

# shell settings
source ./code/code.main/custom-tcshrc

# validate sample sheet
scripts-send2err "Validating sample sheet..."
./code/validate-sample-sheet.tcsh inputs/sample-sheet.tsv
if ($status != 0) then
  scripts-send2err "Errors found in sample sheet, aborting..."
  exit 1
endif

# start pipeline
scripts-send2err "PIPELINE STARTING: `date`"
foreach d (__*)
  set p = `pwd`
  
  # enter directory and run
  cd $d
  ./run
  
  # check for errors
  scripts-send2err "Checking job log files for errors..."
  find results/ -name 'job.*' -print0 | xargs -0 grep -iE 'usage|error|segmentation|not found|join.*sort|no such file|syntax|terminate' >&! error.log
  if (`cat error.log | wc -l` > 0) then
    scripts-send2err "Errors encountered, aborting!"
    exit 1
  endif
  
  # go back to main directory
  cd $p
end
scripts-send2err "PIPELINE COMPLETED: `date`"


