#!/bin/tcsh

##
## USAGE: matrix-pca OUTPUT-DIR SAMPLE-LABELS SAMPLE-MATRICES
##

# shell settings (must be included in all scripts)
source ./code/code.main/custom-tcshrc

# process command-line inputs
if ($#argv != 3) then
  grep '^##' $0
  exit
endif

set out = $1
set labels = ($2)
set matrices = ($3)

# run PCA
scripts-create-path $out/
echo $labels | tr ' ' '\n' >! $out/labels.tsv
scripts-multi-paste $matrices | grep -v '^chr[MYX]' >! $out/matrix.tsv     # TODO: exclude chrM/X/Y?
scripts-perform-pca.r -v -o $out -L $out/labels.tsv --show-text --use-short-names $out/matrix.tsv





