#!/bin/tcsh

##
## USAGE: process-sample-sheet
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

# set path
set path = (./code/code $path)

set sheet = sample-sheet.tsv
set src = `cut -f1 $sheet`
set trg = `cut -f2 $sheet`
cd fastq-or-alignments
set k = 1
while ($k <= $#src)
  rm -f $trg[$k].fastq.gz
  ln -s $src[$k] $trg[$k].fastq.gz
  @ k ++
end
cd ..

