#!/bin/tcsh
#$ -S /bin/tcsh

##
## USAGE: run
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

echo -n "PIPELINE STARTING: "; date

foreach d (__*)
  ( cd $d; ./run )
end

echo -n "PIPELINE COMPLETED: "; date


