#!/bin/tcsh

##
## USAGE: run
##

if ($#argv != 0) then
  grep '^##' $0
  exit
endif

create_path results/
cat easydiff/results/matrices.flank=1kb.nbins=1/easydiff.DSC-E07-H3K27me3:DSC-E15-H3K27me3.norm=none/diff.score | awk '$2<-2' | awk '$4>4 || $5>4 || $6>4' | sort -k4,4rg | cut -f1 | sort -u >! results/row_filter.txt

./code/run.heatmaps



